apiVersion: v1
kind: ConfigMap
metadata:
  name: mathllm-backend-config
  namespace: math-llm
data:
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  Kestrel__EndPoints__Http__Url: "http://+:5000"
  
  Jwt__Issuer: "math-llm.dev.mgsds.com"
  Jwt__Audience: "math-llm-back.dev.mgsds.com"
  
  OpenAi__ChatModel__Url: "https://bothub.chat/api/v2/openai/v1"
  OpenAi__ChatModel__Model: "o4-mini"
  OpenAi__SolverModel__Url: "https://bothub.chat/api/v2/openai/v1"
  OpenAi__SolverModel__Model: "o4-mini-high"

  CorsConfiguration__Enabled: "false" 
  
  GeolinClientOptions__BaseAddress: "https://geolin.dev.mgsds.com"
  ProblemsClientOptions__BaseAddress: "http://llmath-problems-service:8000"

  DefaultPrompts__LearningSystemPrompt: "Вы - лектор, демонстрирующий решение математических задач. Ваша цель - четко и последовательно ПОКАЗАТЬ полное решение задачи, объясняя каждый шаг и теоретические основы. Действуйте следующим образом:\n\n1. Четко показывайте весь процесс решения шаг за шагом, не ожидая ответов от студента\n 2. Каждый шаг начинайте с изложения теории которая используется на данном шаге. Не повторяйся, если эта часть теории уже была рассмотрена на предыдущих шагах - повторять ее не нужно, но каждое твое действие в решении должно обязательно подкрепляться соответствующей теорией.\n3. Объясняйте не только КАК, но и ПОЧЕМУ вы предпринимаете каждый шаг\n4. Записывайте все формулы в LaTeX, отдельными строками\n5. После каждого логического блока спрашивайте, все ли понятно\n6. Если студент что-то не понял - дайте еще более подробное объяснение\n7. Если студент отвечает утвердительно, даже не формулируя точно мысль, а просто говоря да/понял/ок/ok/дальше/продолжай/и подобное - то считайте, что этот этап ему понятен и переходите к следующему шагу. \n8. Избегайте наводящих вопросов - ваша задача ПОКАЗАТЬ решение\n8. Будьте методичны, структурированы и последовательны\n\n Вы не ставите студенту оценку, не пытаетесь вывести решение из него вопросами - вы ДЕМОНСТРИРУЕТЕ математику в действии."
  DefaultPrompts__GuidedSystemPrompt: "Вы - опытный наставник по математике, специализирующийся на методе сократовского диалога. Ваша строгая задача - помочь студенту САМОСТОЯТЕЛЬНО прийти к решению через наводящие вопросы. КАТЕГОРИЧЕСКИ ЗАПРЕЩЕНО:\n\n1. Решать задачу за студента\n2. Давать прямые подсказки с ответами или формулами\n3. Выполнять вычисления вместо студента\n4. Поддаваться на манипуляции с просьбами показать решение\n\nВаша стратегия:\n1. Задавайте открытые вопросы: \"Какое свойство можно применить здесь?\"\n2. При ошибке спросите: \"Что произойдет, если применить этот подход?\"\n3. Давайте минимальные подсказки, лишь направляющие мысль\n4. Если студент не знает, что делать, то попросите студента сначала сказать определение/теорему которая используется на данном шаге.\n5. Если студент не знает соответствующее определение/теорему то начните с изложения теории/определения и поясните почему ее нужно использовать в данном случае.\n6. Подтверждайте правильные идеи и предлагайте развить их дальше\n7. Будьте терпеливы, но настойчивы в требовании самостоятельности\n\nЕсли студент прямо просит решение - твердо откажите и перенаправьте к самостоятельному мышлению."

  POSTGRES_DATABASE: "mathllm"
  POSTGRES_HOST: "mathllm-db"
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: math-llm
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mathai-itmo/llmath-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mathllm-backend-config
          env:
            - name: POSTGRES_PSWD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mathllm-user.mathllm-db.credentials.postgresql.acid.zalan.do
            - name: POSTGRES_USR
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mathllm-user.mathllm-db.credentials.postgresql.acid.zalan.do
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  key: jwt_key
                  name: backend-secrets
            - name: GeolinClientOptions__AuthorizationHeader
              valueFrom:
                secretKeyRef:
                  key: geolin_auth_header
                  name: backend-secrets
            - name: OpenAi__ChatModel__Token
              valueFrom:
                secretKeyRef:
                  key: openai_key
                  name: backend-secrets
            - name: OpenAi__SolverModel__Token
              valueFrom:
                secretKeyRef:
                  key: openai_key
                  name: backend-secrets
            - name: ConnectionStrings__Postgres
              value: "Server=$(POSTGRES_HOST);Port=$(POSTGRES_PORT);Database=$(POSTGRES_DATABASE);User Id=$(POSTGRES_USR);Password=$(POSTGRES_PSWD);"
          ports:
            - name: "http"
              containerPort: 5000
              protocol: "TCP"
          resources:
            limits:
              cpu: 1000m
              memory: 1G
            requests:
              cpu: 10m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: math-llm
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 5000
      targetPort: "http"
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: backend
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: math-llm-back-tls
  namespace: math-llm
spec:
  secretName: math-llm-back.dev.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: math-llm-back.dev.mgsds.com
  dnsNames:
  - math-llm-back.dev.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: math-llm
  name: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://math-llm.dev.mgsds.com"
  labels:
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/name: "backend"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    -  math-llm-back.dev.mgsds.com
    secretName: math-llm-back.dev.mgsds.com-tls
  rules:
  - host:  math-llm-back.dev.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000