---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.14.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: Critical

