---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-local
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: ingress-nginx-local
  targetNamespace: ingress-nginx
  values:
    electionID: ingress-controller-leader
    ingressClass: internal-nginx
    ingressClassResource:
      name: internal-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/internal-ingress-nginx"
    controller:
      allowSnippetAnnotations: true
      config:
        annotations-risk-level: Critical

