apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app.kubernetes.io/name: linkding
    app.kubernetes.io/instance: linkding
    app.kubernetes.io/version: "1.37.0-plus-alpine"
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: linkding
      app.kubernetes.io/instance: linkding
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkding
        app.kubernetes.io/instance: linkding
        app.kubernetes.io/version: "1.37.0-plus-alpine"
    spec:
      serviceAccountName: default
      containers:
        - name: linkding
          image: "sissbruecker/linkding:1.37.0-plus-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: "http"
              containerPort: 9090
              protocol: "TCP"
          env:
            - name: "TZ"
              value: "UTC"
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: linkding.superuser
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: linkding.superuser
            - name: PGSSLCERT
              value: /tmp/postgresql.crt
            - name: LD_DB_ENGINE
              value: postgres
            - name: LD_DB_DATABASE
              value: linkding
            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: linkding-user.linkding-db.credentials.postgresql.acid.zalan.do
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: linkding-user.linkding-db.credentials.postgresql.acid.zalan.do
            - name: LD_DB_HOST
              value: linkding-db
            - name: LD_DB_PORT
              value: "5432"
          volumeMounts:
            - name: linkding-storage
              mountPath: /etc/linkding/data
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources: {}
      volumes:
        - name: linkding-storage
          persistentVolumeClaim:
            claimName: linkding-storage
