---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mittwald
  namespace: default
spec:
  interval: 5m
  url: https://helm.mittwald.de
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-secret-generator
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: kubernetes-secret-generator
      sourceRef:
        kind: HelmRepository
        name: mittwald
      interval: 5m
  releaseName: kubernetes-secret-generator