apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: joplin-tls
  namespace: joplin
spec:
  secretName: joplin.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: joplin.mgsds.com
  dnsNames:
  - joplin.mgsds.com
