---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 85.3.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: prometheus
  targetNamespace: monitoring
  values:
    kubeEtcd:
      enabled: false

    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false

    alertmanager:
      enabled: false

    prometheus:
      service:
        type: "LoadBalancer"
      prometheusSpec:
        retention: 7d
        retentionSize: 50GB
        serviceMonitorSelector:
          matchLabels:
            release: prometheus
        podMonitorSelector:
          matchLabels:
            release: prometheus
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

    grafana:
      envFromSecret: grafana-proxy
      sidecar:
        datasources:
          defaultDatasourceEnabled: false
      additionalDataSources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          isDefault: true
          access: proxy
        - name: Alertmanager
          type: alertmanager
          url: http://prometheus-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
          access: proxy
          jsonData:
            handleGrafanaManagedAlerts: false
            implementation: prometheus
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          url: http://vlogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428
          access: proxy
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: victorialogs
              orgId: 1
              folder: VictoriaLogs
              type: file
              disableDeletion: true
              options:
                path: /var/lib/grafana/dashboards/victorialogs
      dashboards:
        victorialogs:
          victoria-logs-explorer:
            gnetId: 22759
            revision: 1
            datasource:
              - name: DS_VICTORIALOGS
                value: VictoriaLogs
      plugins:
        - victoriametrics-logs-datasource
      persistence:
        enabled: true
        type: sts
        storageClassName: "longhorn"
        accessModes:
          - ReadWriteOnce
        size: 20Gi
        finalizers:
          - kubernetes.io/pvc-protection
      server:
        domain: grafana.mgsds.com
        http_port: 443
        protocol: https
      grafana.ini:
        auth:
          oauth_allow_insecure_email_lookup: true
        server:
          domain: grafana.mgsds.com
          root_url: https://grafana.mgsds.com
