apiVersion: v1
kind: Service
metadata:
  name: radicale
  namespace: radicale
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: radicale
    app.kubernetes.io/instance: radicale
    app.kubernetes.io/version: "3.2.1.0"
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 5232
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: radicale
    app.kubernetes.io/instance: radicale