apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: geolin-tls
  namespace: geolin
spec:
  secretName: geolin.dev.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: geolin.dev.mgsds.com
  dnsNames:
  - geolin.dev.mgsds.com
