apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.88.155-192.168.88.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-homecluster
  namespace: metallb-system
spec:
  ipAddressPools:
  - cluster-pool