apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: directus
  labels:
    app.kubernetes.io/name: directus 
spec:
  type: LoadBalancer
  ports:
    - name: directus
      protocol: TCP
      port: 8055
      targetPort: 8055
  selector:
    app.kubernetes.io/name: directus 