---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: redis
spec:
  interval: 5m
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis
spec:
  chart:
    spec:
      chart: redis-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ot-helm 
      version: 0.21.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: redis
  targetNamespace: redis
