apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-app
  namespace: joplin
  labels:
    app.kubernetes.io/name: joplin
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-app
  template:
    metadata:
      labels:
        app: joplin-app
    spec:
      containers:
        - name: joplin-server
          image: etechonomy/joplin-server:latest
          ports:
            - containerPort: 22300
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: joplin-user.joplin-db.credentials.postgresql.acid.zalan.do
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: joplin-user.joplin-db.credentials.postgresql.acid.zalan.do
          envFrom:
          - configMapRef:
              name: joplin-app-config