apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-app
  namespace: joplin
  labels:
    app.kubernetes.io/name: joplin
    app.kubernetes.io/component: deployment
    app.kubernetes.io/version: 2.17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-app
  template:
    metadata:
      labels:
        app: joplin-app
    spec:
      containers:
        - name: joplin-server
          image: etechonomy/joplin-server:2.17
          ports:
            - containerPort: 22300
          envFrom:
          - configMapRef:
              name: joplin-app-config
          env:
          - name: POSTGRES_PSWD
            valueFrom:
              secretKeyRef:
                key: password
                name: joplin-user.joplin-db.credentials.postgresql.acid.zalan.do
          - name: POSTGRES_USR
            valueFrom:
              secretKeyRef:
                key: username
                name: joplin-user.joplin-db.credentials.postgresql.acid.zalan.do
          - name: POSTGRES_CONNECTION_STRING
            value: "postgresql://$(POSTGRES_USR):$(POSTGRES_PSWD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DATABASE)?sslmode=require"