apiVersion: v1
kind: Service
metadata:
  name: immich-external
spec:
  ports:
  - name: immich
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: immich-external
subsets:
- addresses:
  - ip: 192.168.88.25
  ports:
  - name: immich
    port: 30041
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: immich-ingress
spec:
  ingressClassName: internal-nginx
  rules:
  - host: immich.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-external
            port:
              number: 80