apiVersion: v1
kind: Service
metadata:
  name: truenas-external
spec:
  ports:
  - name: truenas
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-external
subsets:
- addresses:
  - ip: 192.168.88.25
  ports:
  - name: truenas
    port: 80
    protocol: TCP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-tls
spec:
  secretName: truenas.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: truenas.mgsds.com
  dnsNames:
  - truenas.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-ingress
  labels:
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: truenas-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: truenas-proxy/ca-secret
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
spec:
  ingressClassName: external-nginx
  tls:
  - hosts:
    - truenas.mgsds.com
    secretName: truenas.mgsds.com-tls
  rules:
  - host: truenas.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: truenas-external
            port:
              number: 80