kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "wallabag-db"
  namespace: "wallabag"
  labels:
    team: acid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: wallabag-db

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "10Gi"
    storageClass: "longhorn-single"
  users:
    wallabag-user: []
  databases:
    wallabag: wallabag-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
