---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: community-charts
  namespace: actual
spec:
  interval: 5m
  url: https://community-charts.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  chart:
    spec:
      chart: actualbudget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: community-charts
      version: 1.8.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: actual
  targetNamespace: actual
  values:
    persistence:
      enabled: true
      size: 1G
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn
