apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: actual
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: actualbudget
  namespaceSelector:
    matchNames:
      - actual
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s
