apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    server:
      base_url: "https://search.mgsds.com"
      limiter: false
      image_proxy: true
    ui:
      static_use_hash: true
