apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: searxng
data:
  settings.yml: |
    use_default_settings: true
    server:
      base_url: "https://search.mgsds.com"
      limiter: false
      image_proxy: true
    outgoing:
      proxies:
        http: socks5://tor.tor.svc.cluster.local:9050
        https: socks5://tor.tor.svc.cluster.local:9050
    ui:
      static_use_hash: true
