apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baikal-tls
  namespace: baikal
spec:
  secretName: baikal.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: baikal.mgsds.com
  dnsNames:
  - baikal.mgsds.com
