apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepo.yaml
- helmrelease.yaml

# patches:
# - path: add-frontend-ip.yaml
#   target:
#     kind: Service
#     name: longhorn-frontend
#     namespace: longhorn-system