apiVersion: v1
kind: ServiceAccount
metadata:
  name: wakapi
  namespace: wakapi
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/name: wakapi
    app.kubernetes.io/instance: wakapi
    app.kubernetes.io/version: "2.11.2"
