apiVersion: v1
kind: Secret
metadata:
  name: linkding.superuser
  namespace: linkding
  labels:
    app.kubernetes.io/name: linkding.superuser
    app.kubernetes.io/component: secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: Opaque
stringData:
  username: admin
