apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- postgres.yaml
- configmap.yaml
- serviceaccount.yaml
- service.yaml
- deployment.yaml
- ingress.yaml