apiVersion: apps/v1
kind: Deployment
metadata:
  name: trillium
  labels:
    app.kubernetes.io/name: trillium
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trillium
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trillium
    spec:
      containers:
        - name: trillium
          image: zadam/trilium 
          imagePullPolicy: Always
          env:
            - name: RILIUM_DATA_DIR
              value: /home/node/trilium-data
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          volumeMounts:
            - name: trillium-data
              mountPath: /home/node/trilium-data 
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 1G
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: trillium-data
          persistentVolumeClaim:
            claimName: trillium-data
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostpath:
            path: /etc/localtime