apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-storage
  namespace: linkding
  labels:
    app.kubernetes.io/name: linkding-storage
    app.kubernetes.io/component: pvc
    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
