---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: victorialogs
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: victorialogs
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: "6.17.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: victorialogs
      interval: 1h
  values:
    tolerations:
      - operator: Exists
    config:
      clients:
        - url: http://vlogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428/insert/loki/api/v1/push
      snippets:
        extraScrapeConfigs: ""
        pipelineStages:
          - cri: {}
          - decolorize: {}
        extraRelabelConfigs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: service_name
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_label_cluster_name]
            target_label: service_name
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service_name
            regex: (.+)
