apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: victorialogs
  namespace: victorialogs
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-logs-single
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
