apiVersion: v1
kind: Secret
metadata:
  name: directus.secret
  namespace: directus
  labels:
    app.kubernetes.io/name: directus.secret
    app.kubernetes.io/component: secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret
type: Opaque
