apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-storage
  namespace: directus
  labels:
    app.kubernetes.io/name: directus-storage
    app.kubernetes.io/component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: directus-extensions
  namespace: directus
  labels:
    app.kubernetes.io/name: directus-extensions
    app.kubernetes.io/component: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

