kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "findb"
  namespace: "findb"
  labels:
    team: acid
    app.kubernetes.io/name: findb
    app.kubernetes.io/component: database

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "5Gi"
  users:
    findb-user: []
  databases:
    findb: findb-user
  allowedSourceRanges:
  - 192.168.88.0/24

  enableMasterLoadBalancer: true

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
