---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helmforge
  namespace: archivebox
spec:
  interval: 1h
  url: https://repo.helmforge.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: archivebox
  namespace: archivebox
spec:
  interval: 10m
  chart:
    spec:
      chart: archivebox
      version: "1.1.8"
      sourceRef:
        kind: HelmRepository
        name: helmforge
        namespace: archivebox
      interval: 1h
  releaseName: archivebox
  targetNamespace: archivebox
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: longhorn
