apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding-tls
  namespace: linkding
spec:
  secretName: linkding.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: linkding.mgsds.com
  dnsNames:
  - linkding.mgsds.com
