apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: math-llm
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/mgsds/math-llm-backend:latest
          env:
            - name: "OPENAI_MODEL"
              value: "qwen-2.5-7b-instruct"
            - name: "OPENAI_API_KEY"
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM3Y2U4MGI0LTMwZDEtNGFhZi05NTZlLTNmMWU3N2Y1M2RjOSIsImlzRGV2ZWxvcGVyIjp0cnVlLCJpYXQiOjE3NDExMjI3NzgsImV4cCI6MjA1NjY5ODc3OH0.jHI9lFuVsRX237_6iyBmVwHFrzI8_ar7t3yUYdwjuxo"
            - name: "OPENAI_API_ENDPOINT"
              value: "https://bothub.chat/api/v2/openai/v1"
          ports:
            - name: "http"
              containerPort: 5000
              protocol: "TCP"
          resources:
            limits:
              cpu: 1000m
              memory: 1G
            requests:
              cpu: 10m
              memory: 64Mi
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: math-llm
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 5000
      targetPort: "http"
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: backend
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: math-llm-back-tls
  namespace: math-llm
spec:
  secretName: math-llm-back.dev.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: math-llm-back.dev.mgsds.com
  dnsNames:
  - math-llm-back.dev.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: math-llm
  name: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/name: "backend"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    -  math-llm-back.dev.mgsds.com
    secretName: math-llm-back.dev.mgsds.com-tls
  rules:
  - host:  math-llm-back.dev.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000