---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: grafana
    namespace: loki
spec:
    interval: 1h
    url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: loki-stack
      version: '2.10.x'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: loki
      interval: 1h
  values:
    loki:
      auth_enabled: false
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: longhorn
      image:
        tag: 2.9.7
    promtail:
      tolerations:
        - operator: Exists

 