---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: falcosecurity
  namespace: flux-system
spec:
  interval: 1h
  url: https://falcosecurity.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: falco-telegram-secret
      valuesKey: telegramToken
      targetPath: falcosidekick.config.telegram.token
    - kind: ConfigMap
      name: falco-custom-rules
      valuesKey: custom_rules.yaml


  values:
    tty: true

    falcosidekick:
      enabled: true
      webui:
        enabled: true
      config:
        telegram:
          chatid: "-1002680790669"
          minimumpriority: warning