---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  mgsds.override: |
    rewrite name regex (.+)\.mgsds\.com ingress-nginx-controller.ingress-nginx.svc.cluster.local answer auto
