---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-proxy
  namespace: cert-manager
spec:
  encryptedData:
    proxy-url: AgCezYvQmqzNKvt1NBHvL+MauJD1hZ19m8PCpHVabrVL7CBJWbZ2KMW+BMQpqLZ0ezN+eCCdmSFNb/Pm+tOVy9FMJxCyd2HsndrFUWenvbWXAg846c0ieijfQgGjp3QTrnIsVGD4fJqpRdLi/QT+q7KDcMVzRy2cV6g9RkbkKrgNtJRVAqCqSziM5zGoQZA3wx6JrSTXnlvGN+/tv5Q10NvyTuW2VKlgc96xkF02Mqrbk6Nt1FLOnd3Z3K5t34RQcZDTn9N0r+/i16rAyWugCqHoAYSm/gM9QcIZgvudV6WZLChCouc2lXBGR7cdWN70ZLkYxP2tBEEYRTgXjsKh1BSavgHvjaGqDD/9VFJlBgHFuq4zWWQq3HFg1pzxnKgKh8Wv1LpBOqJBpsrkNVxUr3HbItEHYzuOwwqpxSHf9vT4QSUZfMqWVTy8zwJ06AGHwFRMCLi3cQ2GLxRcv7wC1LJQrnm15Okk0rjSOWvVvMFJLcRiINIW8kUXwS5VodSdvBMxcUQphbHiWrCvSl65JS+bVCJ68c0BOb5U5a8cYAwQ9nYtBKWjlmTPdtWooh02q2Jgoe6qpsYJrocUC4qSU1yg+yqDfJVtTA+r01BHw2r4SuirfE5fV3Gla5TB6A3fg5DpZZQvowvQlZ5tBjcEkQaVVk7MRSwdKSOyvOyVGI0W/EwRkoNJwaFwph8bQyUkPEApkbJ9joJEPZwRKBHdQG0xl1L1APGLSq0V8rO5jWCHJeGzBAXwEauz/lZ5TWBi62I=
  template:
    metadata:
      name: cert-manager-proxy
      namespace: cert-manager
