---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-proxy
  namespace: cert-manager
spec:
  encryptedData:
    proxy-url: AgAzHa2bBdtYOG14BfisZi+xzfORcflZc0k3EujwmbNu4T+woIU0C6cvtVZH/CCh+kyhnQj669JaRpfFvEfs7lEJFKZg3FIs6Wpr8l6NEyem2bvi7QyxehjNo+Z4zPqMewhrf9MuK1FJ+cBFmsXWj2UwCDKaOvVXeYJ1LNNeufgVC7BvlZ7l7CJL9lNJgR2HL5pm4N4OceZKW0MP71HxZlYHfCKr45/rcv0HZht+jcmlFcFPKxl55o9CGPo8GShNRVe3mzLOUfyOUYC2eSkiJVkJ9l/EXp8bfjeBD7PKyx1I6zJ01drHp3e+j1tufX7rKA14A0DyBqLlHP4CVzyhz2c0d4yfkG3179oi+z4DM7oY9iZ9GZB4/9vX9Fl5P61jBgv7A3tXrAq8vFV79nerG8LwlJbDLYLoXSz42kBnOTnAkzAvVzL5GjULMfExkH2Wae58NIASG3/d/aP8FiDuSycs/x6tlVMuBrAH6KsicXCOq0++9BYBncD/MNP3lzitPFsZ5fezRh17dOiOptPcl6uNb1vdrSz8QIPeuTM+kLClKSz9Vcfxxz520hNTyZ9Fd/m/braHPbjtxEs3Y1kOODgfp8nPYTD2LoKjKxGtTYjYMiIFuw9ZccNmmylBekSnlTiPRsqHApe0ITWAdUtCn6iFkzbgUd9lTFDjoNYBXzfOYi0jUasEn0CWsb8g/WpBBfnIavsddEqNp/+Bhxt8yr+cKX1GqWgCCosyUY96+OYc4/TValbXGlHwmHlU5Nup47pAMADTe+Xpe9Hi1A63H+odd0L0
  template:
    metadata:
      name: cert-manager-proxy
      namespace: cert-manager
