apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-tls
  namespace: truenas-proxy
spec:
  secretName: nas.mgsds.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nas.mgsds.com
  dnsNames:
  - nas.mgsds.com
  - cloud.mgsds.com
  - immich.mgsds.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: truenas-proxy
  name: truenas-ingress-mtls
  annotations:
   cert-manager.io/cluster-issuer: letsencrypt-prod
   nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
   nginx.ingress.kubernetes.io/auth-tls-secret: truenas-proxy/ca-secret
   nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
   nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
  labels:
    app.kubernetes.io/name: truenas-ingress-mtls
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nas.mgsds.com
    - immich.mgsds.com
    secretName: nas.mgsds.com-tls
  rules:
  - host: nas.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: truenas
            port:
              number: 80
  - host: immich.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: truenas
            port:
              number: 30041
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: truenas-proxy
  name: nextcloud-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 51200m   
    nginx.ingress.kubernetes.io/server-snippet: |-
       server_tokens off;
       proxy_hide_header X-Powered-By;
    nginx.ingress.kubernetes.io/cors-allow-headers: X-Forwarded-For
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 225m
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  labels:
    app.kubernetes.io/name: truenas-ingress
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cloud.mgsds.com
    secretName: nas.mgsds.com-tls
  rules:
  - host: cloud.mgsds.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: truenas
            port:
              number: 30027
