---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-proxy
  namespace: flux-system
spec:
  encryptedData:
    url: AgBqRP8SwHueRljnnTlUUHbyGc6RmI6RqtdEsAuzf5r5irEJB2tDPZ/OvlsiRXFBSamSm69b1KkqRce2Bl4Hl7nBhYBtvb27UJiM6+O7orxPbRcxx6LGAJ3N47ZsyaUxbsX0uHwSHa32dYKUsJXZVflWJo5aR/Z0iW69mOX7Egqc9ituBb7NcJ6BHNKHnqzOAwe65tmQIuJ4e92Y1N07RKqOazFjORj6A3p7Rf6MYPw1Eodwx6mTNAL+wG89jB4BAT6g8E/J99Xt5uJ1o5qiF184ysWyofS8+uRQGVfucF1cTvVIk+HVp4bYI+qhAosjRtkmCkU5Yp4E2F0ERU6+NRWF2pDF+Yvs/zuIJnvNDNGeIysT6uUHWteXc+5p29NQcIqi6sh4TQeCSYCQiFdObQo0wqA/sQ17At4FtYCbY1i1y2VfgUGxR6hI1HZs8wkrSmkXPRGSoipbOLlaWsgTjhIyvo+b15ZU4yyUWc8QbsVDZRFhLZ/t4CqMeOQMalYHXwC/wTVRFqjPb1NFOvmOg47aJ33xFRaBIz/UPSbBhYzWPugFHia5IAA/xk0aYTecQkHtHSbbw8a3Gp2AfmYBbhG6ja9bpKamYLMTmDX+8j7XIRUIkyKUVIy7YvU/xM0yhwuBs0b6hexau4kS/DyPkqZV9GMBvK6pB/7pLB0WhsBTf8nFousMiF2ussJddI2zAJosIVweILB6NF7jReGYEhzt7y3wl8DidSy1wL2raTsrwjavaFIC0OvPnnhsdwLgbJXAvrzum6C0B0Q+r6xa
  template:
    metadata:
      name: telegram-proxy
      namespace: flux-system
