apiVersion: v1
kind: Service
metadata:
  name: mktvis
  namespace: mktvis
  labels:
    app.kubernetes.io/name: mktvis
    app.kubernetes.io/component: service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mktvis
  ports:
    - name: http
      port: 80
      targetPort: http
