---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    adminToken: AgChluKuRtB2IkZInA1CfoX4k5iHXHmPW3Hi+F6lfcTq+tCNugFbrup3UIo83qz2+jWX8DF7OA9pizawIyEuxoHUdUw3TfiLbDka8wiyWKOes8qXA7khhlgwMwsSqGIJ1VjUFUGsQiGJjWGl70VMiP1fZUZ1Xd6HpZkg7WjDDuVWDCz/bjKrK9EyOtj71hxBtaPOhh2VWJL/rAjGhQa9GCGGzamh7aswn4nlEV625zxrZW0jP0FvsoUUr8YBL49R6DbUlwn3Mn0tQnOxQvq7dxb0h74iQWhb2vBPMWus/G79PRDYwvDq+px5jQ3TZLkkubfL9SIH/jBKlJj/3wH/Xajqzz1dU+b+u3P0qLhWSBkZrA7YnPO4daroytYAsKdUcJ13QEV4nGhT8XyKtn1YvJn2q0K+J6ByTbPUJXQTnSqWjjMf9MvH8yrDWPIMd2U8hFZvrVutCxyqhcQ9xjT6GcOzgIjHXdvNV4Bjs5jitXG82ynrwyFijOgMrNzA8qPhEbPx1fVW6rZ1mp9WsIxqDfV8MGn7wESRROmMGZRqtxGilCcg6O0Q6gBnpdt9wTBGjmVadVXKDpJmheiSqaTRRMdXs37ll/jU2LQeJflDdzoTxX0PRXPw8p7ziG/Bs0dgsALyABr3x2A7rkPt0kK9XLqHHOJcrbZN4o9wAXL4fKPlGAmkjjSYqHkFaldVc7DNo7VVSH6mwZ4HGrRGcDpyFoQd/uc6oe7lEp5nAS9RkniN2CHFUb29htx5Ay9f7L8L//imtrKsdF/cLlZ8KCT2ylaV3LJb5SN7/VBtAxSSBYuUxxhMLeDJyTdojBmtzsmSAvQBctBF2m7+YagxZkPa4LOu2ClifA7gK9ymdHVUttBE3QlKFi6D4w==
  template:
    metadata:
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
