apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/longhorn/longhorn/v1.7.2/deploy/longhorn.yaml
- servicemonitor.yaml

patches:
- path: add-frontend-ip.yaml
  target:
    kind: Service
    name: longhorn-frontend
    namespace: longhorn-system