---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.3
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      allowSnippetAnnotations: true
      ingressClassResource:
        name: external-nginx
        controllerValue: "k8s.io/external-ingress-nginx"
        default: false
      extraArgs:
        controller-class: "k8s.io/external-ingress-nginx"
        watch-ingress-without-class: "false"
      electionID: ingress-controller-leader-external
      ingressClass: external-nginx
      config:
        annotations-risk-level: Critical
