---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-local
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.12.3
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: ingress-nginx-local
  targetNamespace: ingress-nginx
  values:
    controller:
      allowSnippetAnnotations: true
      ingressClassResource:
        name: internal-nginx
        default: false
      ingressClass: internal-nginx
      config:
        annotations-risk-level: Critical


