apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- pvc.yaml
- postgres.yaml
- service.yaml
- deployment.yaml
- certificate.yaml
- ingress.yaml
- servicemonitor.yaml