apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wallabag
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wallabag
  namespaceSelector:
    matchNames:
      - wallabag
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s
