---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox-oidc
  namespace: homebox
spec:
  encryptedData:
    client-id: AgBzqLc2vLQc/ChBZ7+ieEew791PERqPCUl1mo2WXSNmnkkcNGss9sjppW9vJ66R86wcK7YRROLvB8ZvsJ//SYm8QFG3OEOItTwA6xMKjioEWUA1F4HCvoNa84+jnFmLm9vHjmR1tFDwC2YQwSDRLlHO6rSz7nFuMuDhAVxrSEUI76F4Bo9axh7283/ZQHwpZGwTV55VmP9KgswegXY3/e0Hb8nQlgrkfrJID+bwc0E2xxjUxyj0sMwyWXe9u55VATQXAtj/WyGOJtEtlg+4trqyTRKu+mCUalD9bySKcxFAYeS/yk/lf1mC8JzYdpafeoej5autFwTLSTT7u7FNRsQPiWL5Tcbf6m3ij/q2AgopSUHsADRANu6+LJsq4aC+voiMkMXmhrr8XBCK2VL59lvf9x1i6yUN6ROikj1+Wcl3WKWEyU5ejGv3dI1Ce2fvDKfed5mkvdPMVL6366gvP+cOLQBZrJXIDF2QO4Ru7aCWHURhPggXds6AcqypJWGxTQb+n5SwUNgN5o6a5y6SPZaOS7Hu/I14c3FgOAhKQ1HdcW2nOCJcV/9bocGpnHFUFaz9wQALZ2mEjPhe4z3D+3p25rgC1udpx1ybtJpOCxQoXlGt9ebHbvwtB4fLgQ57hW20luGColeCaNC8TE1v+SX5fd9ttcHZ+TkyK/vEJNIO9rKoW8ZbOAF1n9jvyyRuyMLMQ6jfdxakbffq4uA4ULj01IlktWp4WjStXO4zolKHjDZjdBM=
    client-secret: AgDf/IFnTmtEc+rv169SD47quwNjqh8bmoiuZWHhSv9EKTt+NEE+UwhLZsuDSckhnkgLduL+a92YoKmIrQSpJCVBLWGzp2yYStxxKM0YQ1rpU5HieI7k3/pLWh1476mmsQiDYCt341wKqQPx2rYL7sc+MdpAyeQTK6HY52yuv59GwvSLRcsATUPENC5HgSCSKf/p3s671xujddhBTxAQHVNVKsQmYFu0IXq72mPDy+wsyz3Z+ZsU9NRgzlH+P/qdaoQk25SwpPpjwtA0Gf7gNT/+p5luFTdnIeBjHsgPU7+5tvuhZlB3l5Ndw8ul7gOX9Iq29DVVkhIGGbhamWR3AzJ22JwploTZt7axLUxHQJccjefVcUYpeyi9Hgm7n6iIUCS8aNpSLgVVkdxdIL7hHG4/G6rg0+XECKuN5D2tgMuLNDxiQUbPM9Qqui2V7453Qx9TY4FDCvG51p+wxB4taAjfuCNeY032TNTy+1UAepobQDdJzoHCKHtInpp2GVTYQVQfg8NaeescLOVzGl8dqLDfZMpPrTuu8ElOaxRHZ51mEl0ec7QexX8tGgSPxFsrN4DCDgdwVOegvn79mJBfLq5krDk25jEdf+Tav847qojLTfKRhihwvul2jwGws1C+EypbsBVycD3KrYqE0J2IdFZmwhc3LIlqRXqmu92u3082yr7UXWHas8/8jNU4/s23w8ugLTJ3ZgvS0babZy1ULifKPDju8JZbKCbXUQn4MzwYFg==
  template:
    metadata:
      name: homebox-oidc
      namespace: homebox
