---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truenas-exporter
  template:
    metadata:
      labels:
        app: truenas-exporter
    spec:
      containers:
        - name: graphite-exporter
          image: prom/graphite-exporter:latest
          args:
            - --graphite.mapping-config=/etc/graphite-exporter/graphite_mapping.conf
            - --graphite.listen-address=:2003
            - --web.listen-address=:9109
          ports:
            - containerPort: 2003
              name: graphite
              protocol: TCP
            - containerPort: 9109
              name: metrics
          volumeMounts:
            - name: mapping
              mountPath: /etc/graphite-exporter
              readOnly: true
      volumes:
        - name: mapping
          configMap:
            name: graphite-mapping
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
  labels:
    app: truenas-exporter
spec:
  type: LoadBalancer
  selector:
    app: truenas-exporter
  ports:
    - name: graphite
      port: 2003
      targetPort: 2003
      protocol: TCP
    - name: metrics
      port: 9109
      targetPort: 9109
