---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-exporter-config
  namespace: truenas-exporter
spec:
  encryptedData:
    truenas-exporter.yml: AgCjkQAV3+vS2I+qi/YE+QSyiIXFxZk/9RNL0slXwJwJTe85cWEpNEtonMB7gI9PUPCjq+ZmqIDd/643V9PNJXCVW9Hb1LFJVzbKg0u8X73JVsmVBbVR6394qM9A8SFF8hL0O9TVoeKQ2ZV9JQqsl6Z3hRvD+uUF1QuLDaNhfzSYPvMnXmoMLNkt9O/B6RYM/499Rb0WEbJ26j9N3mIIOz9LpYU23fg5vyncFexKrQM4mNr0f1omJvztcsMYNAj7skPNdx/x2PC8bYzOxz2vu1g5vC5z/LjVV34kDF6CS2VrN8/rMHquC3okiPgJjNLN9Ur4cz8VmTuh+LrY7xPm0X4neiovkls4loPhZTKnEH1nLwRWXbqjeFAwGzpjLvpgInkV935kld6enuPoTSEsI5hbiUIn38M0hmDqQL+sqIZXZHeWYj3p74E2M7PPCMOigEenoWsVz0PlYyfZlrJvy8ilGwKqedwmv4NMFJNwiXbrEQuEBfztJDhtWEITGxMC+XEn3OLYWROAg58YWfWMzRvLfFapvlKnCokZyGqSES7qGe4y0zmdN9MPQmz+SWz5JJhBbfy2dOYV/kDKlF/kV6LX/PWDzAfHXMhkQBsE+SgSjHnzuUsHELtG+Isw2IsLSGXY30bF88JGhbjO4YnvfEnR/Xe+6K/kmeXS+snRNsuAbKRtjxhSd21JZgYE3AUaxgqxHoGjDMZFBed1aDg6nY+Q7+fDWXaYTZFmofTw/y3MiSx0pWc2JdEUAM9eB1/5Y7KjohXutHCpfrrxv3xFWrHOSmNHlykPPHCETvgXuw1qElzNqDkGaGxtbThTadvCu+Bi7w4xX/VxVKYbPiVYMfFNNzu+1oI8iB7jYXxzHgC/zCMw4WQfajeqDbF/JsYM+NzSq/ZLeaZ+MdxlYpttzg==
  template:
    metadata:
      name: truenas-exporter-config
      namespace: truenas-exporter
