apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-exporter
  namespace: truenas-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: truenas-exporter
  namespaceSelector:
    matchNames:
      - truenas-exporter
  endpoints:
    - port: metrics
      interval: 60s
