kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: vaultwarden-db
  namespace: vaultwarden
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 1
  volume:
    size: "2Gi"
  users:
    vaultwarden-user: []
  databases:
    vaultwarden: vaultwarden-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi