kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "wakapi-db"
  namespace: "wakapi"
  labels:
    team: acid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: wakapi-db

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    wakapi-user: []
  databases:
    wakapi: wakapi-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
