apiVersion: v1
kind: Service
metadata:
  name: wakapi
  namespace: wakapi
  labels:
    app.kubernetes.io/component: service
    app.kubernetes.io/name: wakapi
    app.kubernetes.io/instance: wakapi
    app.kubernetes.io/version: "2.11.2"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: wakapi
    app.kubernetes.io/instance: wakapi
