apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:latest
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              value: https://vikunja.mgsds.com
            - name: VIKUNJA_DATABASE_HOST
              value: vikunja-db
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-user.vikunja-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: VIKUNJA_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: vikunja-user.vikunja-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: VIKUNJA_DATABASE_TYPE
              value: postgres
            - name: VIKUNJA_DATABASE_DATABASE
              value: vikunja
            - name: VIKUNJA_DATABASE_SSLMODE
              value: require
            - name: VIKUNJA_SERVICE_JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: vikunja-secrets
                  key: jwt-secret
          volumeMounts:
            - name: files-storage
              mountPath: /app/vikunja/files
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: 3456
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: files-storage
          persistentVolumeClaim:
            claimName: vikunja-pvc
      restartPolicy: Always