kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "vikunja-db"
  labels:
    team: acid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: vikunja-db

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "100Mi"
  users:
    vikunja-user: []
  databases:
    vikunja: vikunja-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
