kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: pocket-id-db
  namespace: pocket-id
  labels:
    team: acid
    app.kubernetes.io/component: database
    app.kubernetes.io/name: pocket-id-db

spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 1
  volume:
    size: "2Gi"
  users:
    pocket-id-user: []
  databases:
    pocketid: pocket-id-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi